#+title: The Comparison Tests
#+author: Chase Mathison
#+date: 11 April 2024
#+email: cmathiso@su.edu
#+options: H:2 ':t ::t <:t email:t text:t todo:nil toc:nil 
#+startup: showall
#+startup: indent
#+startup: hidestars
#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [presentation]
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %5BEAMER_act(Act) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \definecolor{SUred}{rgb}{0.59375, 0, 0.17969} % SU red (primary)
#+latex_header: \definecolor{SUblue}{rgb}{0, 0.17578, 0.38281} % SU blue (secondary)
#+latex_header: \setbeamercolor{palette primary}{bg=SUred,fg=white}
#+latex_header: \setbeamercolor{palette secondary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette tertiary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette quaternary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{structure}{fg=SUblue} % itemize, enumerate, etc
#+latex_header: \setbeamercolor{section in toc}{fg=SUblue} % TOC sections
#+latex_header: % Override palette coloring with secondary
#+latex_header: \setbeamercolor{subsection in head/foot}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{date in head/foot}{bg=SUblue,fg=white}
#+latex_header: \institute[SU]{Shenandoah University}
#+latex_header: \titlegraphic{\includegraphics[width=0.5\textwidth]{\string~/Documents/suLogo/suLogo.pdf}}
#+latex_header: \newcommand{\R}{\mathbb{R}}

* Announcements
** Announcements
1. Homework due, and new homework in MyOpenMath.
2. Office hours, 10am - 11am.

* Lecture
** The Comparison Test
Now that we have some series for which we can describe their
convergence/divergence, let's look at another test for convergence!

** The Comparison Test                                           :B_theorem:

Let \(\sum\limits_{n=1}^{\infty} a_n\) be a series with \( a_n \ge 0\) for all \(n\), and suppose
\(\sum\limits_{n=1}^{\infty} b_n\) is another series which we know is convergent.

Then, if there is an \(N\) such that \(a_n\) _\hspace*{0.25in}_ \(b_n\) for all \(n \ge N\), then
\[
\sum\limits_{n=1}^{\infty} a_n\]
_\hspace*{1in}_.

Similarly, if \(\sum\limits_{n=1}^{\infty} b_n\) is a series which we know is divergent,
and there is an \(N\) such that \(a_n\) _\hspace*{0.25in}_ \(b_n\) for all \(n \ge N\), then
\[
\sum\limits_{n=1}^{\infty} a_n\]
_\hspace*{1in}_.

** Example
Discuss the convergence/divergence of
\[
\sum\limits_{n=1}^{\infty} \frac{1}{n!}.\]
\vspace{10in}

** Example
Discuss the convergence/divergence of
\[
\sum\limits_{n=1}^{\infty} \frac{\sin^2(n)}{n^2}\]
\vspace{10in}

** Example
Discuss the convergence/divergence of
\[
\sum\limits_{n=2}^{\infty} \frac{1}{\ln(n)}\]
\vspace{10in}

** The Limit Comparison Test
The comparison test is nice, but it's a little too simplistic sometimes.  For instance,
if we want to examine the convergence/divergence of the series
\[
\sum\limits_{n=2}^{\infty} \frac{1}{n^2-1}\]
then our natural instinct is to compare this series to \(\sum\limits_{n=2}^{\infty} \frac{1}{n^2},\)
but
\[
\frac{1}{n^2-1} \hspace{1in} \frac{1}{n^2}\]
so the comparison test wouldn't tell us anything here.  This is where the limit comparison
test is useful!

** The Limit Comparison Test

Suppose \(\sum\limits_{n=1}^{\infty} a_n\) and \(\sum\limits_{n=1}^{\infty} b_n\) are series with \(a_n,b_n \ge 0\).
Let \(M = \lim_{n\rightarrow \infty} \frac{a_n}{b_n}\).  Then
1. If \(M > 0\), is a real number, then
   \( \sum\limits_{n=1}^{\infty} a_n \text{ and } \sum\limits_{n=1}^{\infty} b_n\)
   have the _\hspace*{1in}_.
2. If \(M = 0\) and \(\sum\limits_{n=1}^{\infty} b_n\) converges, then
   \(
   \sum\limits_{n=1}^{\infty} a_n\)
   _\hspace*{1in}_.
3. If \(M = \infty\) and \(\sum\limits_{n=1}^{\infty} b_n\) diverges, then
   \(
   \sum\limits_{n=1}^{\infty} a_n\)
   _\hspace*{1in}_.

** Example
Use the limit comparison test to discuss the convergence/divergence of the series
\[
\sum\limits_{n=2}^{\infty} \frac{1}{n^2-1}\]
\vspace{10in}

** Example
Use the limit comparison test to discuss the convergence/divergence of the series
\[
\sum\limits_{n=2}^{\infty} \frac{1}{2^{\ln(\ln(n))}}\]
\vspace{10in}

** Example

