#+title: Volumes of Revolution: The Disk Method
#+author: Chase Mathison
#+date: 6 February 2024
#+email: cmathiso@su.edu
#+options: H:2 ':t ::t <:t email:t text:t todo:nil toc:nil 
#+startup: showall
#+startup: indent
#+startup: hidestars
#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [presentation]
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %5BEAMER_act(Act) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \definecolor{SUred}{rgb}{0.59375, 0, 0.17969} % SU red (primary)
#+latex_header: \definecolor{SUblue}{rgb}{0, 0.17578, 0.38281} % SU blue (secondary)
#+latex_header: \setbeamercolor{palette primary}{bg=SUred,fg=white}
#+latex_header: \setbeamercolor{palette secondary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette tertiary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette quaternary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{structure}{fg=SUblue} % itemize, enumerate, etc
#+latex_header: \setbeamercolor{section in toc}{fg=SUblue} % TOC sections
#+latex_header: % Override palette coloring with secondary
#+latex_header: \setbeamercolor{subsection in head/foot}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{date in head/foot}{bg=SUblue,fg=white}
#+latex_header: \institute[SU]{Shenandoah University}
#+latex_header: \titlegraphic{\includegraphics[width=0.5\textwidth]{\string~/Documents/suLogo/suLogo.pdf}}


* Announcements
** Announcements
1. Homework!
2. Office hours!

* Volumes of revolution
** Volumes of revolution
One type of solid that comes up a lot in real life is a solid that is
generated by rotating a region about an axis.

One example of this is the unit sphere: it can be generate by rotating
a upper half circle of radius 1 and the area underneath it about the
\(x- \)axis. 

Really, any object that has circular cross sections can be generated
in this manner.  Because of this, what we learned last week will apply
to these _\hspace*{1in}_. The volume of a solid of revolution
will be called a _\hspace*{1in}_.

Let's look at a specific example before moving on to the general
method.

** Example
Find the volume of the solid generated by rotating the region bounded
by the curves
\[
y = \frac{1}{x},\, x = 1,\, x = 2,\, y = 0 \]
about the \(x- \)axis by using the method of slicing.
\vspace{10in}

** Example

** The disk method
The main difference between what we're talking about today, and what
we talked about last time, is that we know beforehand with a solid of
revolution that the cross-sectional areas are going to be circles.

Let's look at a general curve, and the volume that results from it
when we rotate the region of interest about the \(x- \)axis:
\vspace{10in}

** The disk method

** The disk method
We have shown the following
*** The disk method                                             :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:

Let \(f \left( x \right) \) be continuous and non-negative.  Let \(R
\) be the region bounded above by the graph of \(f \left( x \right)
\), below by the \(x- \)axis and by the curves \(x = a \) and \(x=b
\).  Then, the volume of the solid that is generated by rotating \(R
\) about the \(x- \)axis is given by
\[
\, \]
\phantom{butts}

\phantom{butts}


** Example (Volume of a circular cone)
Find the volume of the solid that is generated by rotating the region
in the first quadrant that is bounded above by \(y = -\frac{r}{h}x + r \)
about the \(x- \)axis, where \(r \) and \(h \) are constants.
\vspace{10in}

** Example

** Example
Find the volume of the solid that is generated by rotating the region
bounded by the curves \(y = \sin \left( x \right) \), \(y = 0 \), \(x
= 0 \) and \(x = \pi \) about the \(x- \)axis.

#+BEGIN_SRC python :exports none :results output :eval no-export
import matplotlib
matplotlib.use('Agg')
from matplotlib import rc
rc('font',**{'family':'serif','serif':['cm','Palatino']})
rc('text', usetex=True)
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

x = np.linspace(0,np.pi,1000)
t = np.linspace(0,2*np.pi,1000)
u,v = np.meshgrid(x,t)
X = u
Y = np.sin(u)*np.cos(v)
Z = np.sin(u)*np.sin(v)

fig=plt.figure()
ax = fig.gca(projection='3d')
ax.set_xlim3d(0,np.pi)
ax.set_ylim3d(-1,1)
ax.set_zlim3d(-1,1)
ax.plot_surface(X,Y,Z,cmap='viridis',shade=True)
plt.savefig('../img/day006-ex01.png')

#+END_SRC

#+RESULTS:

#+BEGIN_EXPORT latex 
\begin{center}
\includegraphics[width=0.5\textwidth]{../img/day006-ex01.png}
\end{center}
#+END_EXPORT
\vspace{10in}

** Example

** Example
Find the volume of the solid generated by rotating the region bounded
by the curves \(y = \sqrt{x} \), \(y = 0 \), \(x = 0 \) and \(x = 3 \)
about the \(x- \)axis.

#+BEGIN_SRC python :exports none :results output :eval no-export
import matplotlib
matplotlib.use('Agg')
from matplotlib import rc
rc('font',**{'family':'serif','serif':['cm','Palatino']})
rc('text', usetex=True)
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

x = np.linspace(0,3,1000)
t = np.linspace(0,2*np.pi,1000)
u,v = np.meshgrid(x,t)
X = u
Y = np.sqrt(u)*np.cos(v)
Z = np.sqrt(u)*np.sin(v)

fig = plt.figure()
ax = plt.gca(projection='3d')
ax.set_xlim3d(0,3)
ax.set_ylim3d(-np.sqrt(3),np.sqrt(3))
ax.set_zlim3d(-np.sqrt(3),np.sqrt(3))
ax.plot_surface(X,Y,Z,cmap='viridis',shade=True)
plt.savefig('../img/day006-ex02.png')
#+END_SRC

#+RESULTS:

#+BEGIN_EXPORT latex 
\begin{center}
\includegraphics[width=0.5\textwidth]{../img/day006-ex02.png}
\end{center}
#+END_EXPORT
\vspace{10in}

** Example

** The disk method for functions of \(y \)
We can use this exact same method to find the volume of solids of
revolution generated by rotating regions about the \(y- \)axis.  
When we do this, we need to make sure to write our functions in terms
of _\hspace*{1in}_.  This will give us the following rule: 

*** Disk method (in terms of \(y \))                           :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
Let \(g \left( y \right) \) be continuous and nonnegative. Defined \(Q
\) to be the region bounded on the right by the graph of \(g \left( y
\right) \), on the left by \(x = 0 \), and between \(y = c \) and \(y
= d \).  Then the volume of the solid generated by rotating \(Q \)
around the \(y- \)axis is given by
\[
\, \]
\phantom{butts}

** Example

Find the volume of the solid generated by rotating the region bounded
by the curves \(y = \sqrt{1 + x} \), \(x = 0 \), and \(y = 2 \) about
the \(y- \)axis.

#+BEGIN_SRC python :exports none :results output :eval no-export
import matplotlib
matplotlib.use('Agg')
from matplotlib import rc
rc('font',**{'family':'serif','serif':['cm','Palatino']})
rc('text', usetex=True)
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

y = np.linspace(1,2,1000)
t = np.linspace(0,2*np.pi,1000)
u,v = np.meshgrid(y,t)
X = (u**2-1)*np.cos(v)
Y = u
Z = (u**2-1)*np.sin(v)
fig = plt.figure()
ax = plt.gca(projection='3d')
ax.set_xlim3d(-3,3)
ax.set_ylim3d(1,2)
ax.set_zlim3d(-3,3)
ax.plot_surface(X,Y,Z,cmap='viridis',shade=True)
plt.savefig('../img/day006-ex03.png')
#+END_SRC

#+RESULTS:

#+BEGIN_EXPORT latex 
\begin{center}
\includegraphics[width=0.5\textwidth]{../img/day006-ex03.png}
\end{center}
#+END_EXPORT
\vspace{10in}

** Example

** Next time
Next time we'll talk about how to find the volume of even more
complicated volumes of revolution using the /washer method/ (of which
the disk method is just a special case).

Make sure to get started on the homework!
