#+title: Arc Length
#+author: Chase Mathison
#+date: 18 March 2024
#+email: cmathiso@su.edu
#+options: H:2 ':t ::t <:t email:t text:t todo:nil toc:nil 
#+startup: showall
#+startup: indent
#+startup: hidestars
#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [presentation]
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %5BEAMER_act(Act) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \definecolor{SUred}{rgb}{0.59375, 0, 0.17969} % SU red (primary)
#+latex_header: \definecolor{SUblue}{rgb}{0, 0.17578, 0.38281} % SU blue (secondary)
#+latex_header: \setbeamercolor{palette primary}{bg=SUred,fg=white}
#+latex_header: \setbeamercolor{palette secondary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette tertiary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette quaternary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{structure}{fg=SUblue} % itemize, enumerate, etc
#+latex_header: \setbeamercolor{section in toc}{fg=SUblue} % TOC sections
#+latex_header: % Override palette coloring with secondary
#+latex_header: \setbeamercolor{subsection in head/foot}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{date in head/foot}{bg=SUblue,fg=white}
#+latex_header: \institute[SU]{Shenandoah University}
#+latex_header: \titlegraphic{\includegraphics[width=0.5\textwidth]{\string~/Documents/suLogo/suLogo.pdf}}
#+latex_header: \newcommand{\R}{\mathbb{R}}
#+latex_header: \usepackage{tikz}

* Announcements
** Announcements
1. Exam next week!
2. Office hours, 10am - 11am.
   
* Arc length
** Arc length
Now we're going to switch back to talking about applications of integration.  First up: arc length.

It's easy to calculate the length of a straight line.  
For instance, what is the length of the line segment given below?

#+BEGIN_EXPORT latex 
\begin{tikzpicture}[scale=2.5]
\draw[help lines,step=0.2] (-1,-1) grid (1,1);
\draw[thick,->] (-1,0) -- (1,0) node[below,right] {\(x \)};
\draw[thick,->] (0,-1) -- (0,1) node[above] {\(y \)};
\draw[thick,color=red] (-0.3,-0.5) node[below,left] {$(-0.3,-0.5)$} -- +(.3,.4) node[right] {$(0,-0.1)$};
\fill[red] (-0.3,-0.5) circle (1pt);
\fill[red] (0,-0.1) circle (1pt);
\end{tikzpicture}
#+END_EXPORT

** Arc length
Now, how could we try to calculate the length of the following curve
\(y = f(x) \)?

#+BEGIN_EXPORT latex 
\begin{tikzpicture}[scale=2.0]
\draw[help lines, step=0.25] (-1,-1) grid (1,1);
\draw[thick,->] (-1,0) -- (1,0) node[right] {\(x\)};
\draw[thick,->] (0,-1) -- (0,1) node[above] {\(y \)};
\draw[thick,color=red] (-0.9,-1) to [out=45,in=-130] (0,0.2) to [out=50,in=180] (0.3,0.3) to [out=0,in=135] (1,-0.4);
\foreach \x in {-1,-0.5,...,1}
  \node[below] at (\x,-1) {$\x$};
\foreach \y in {-1,-0.5,...,1}
  \node[left] at (-1,\y) {$\y$};
\end{tikzpicture}
#+END_EXPORT

We don't know how this curve is defined, but we can try to approximate
the length using some straight lines, which are easy to calculate the
length of.

** Arc length

#+BEGIN_EXPORT latex 
\begin{tikzpicture}[scale=5]
\draw[clip] (0,0) circle (0.5cm);
\draw[help lines, step=0.25] (-1,-1) grid (1,1);
\draw[thick,color=red] (-0.5,-0.5) to [out=45,in=-130] (0,0.2) to [out=50,in=180] (0.3,0.3) to [out=0,in=135] (0.9,-0.4);
\end{tikzpicture}
#+END_EXPORT

** Arc length

** Arc length
All of this has shown the following:
*** Arc length of the graph of a smooth function                :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:

Let \(f \left( x \right) \) be a differentiable function such that
\(f' \left( x \right) \) is continuous (i.e. \(f \) is /smooth/) over
the interval \(\left[ a,b \right]. \) The arc length of the portion of
the graph of \(y = f \left( x \right) \) between the points \( \left( a,f
\left( a \right) \right) \) and \( \left( b,f \left( b \right) \right)
\) is given by
\[
s = \int\limits_a^b \sqrt{1 + \left[ f' \left( x \right) \right]^2}\,dx. \]

*** :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
A word of warning:  many of the integrals that result from this
theorem are very difficult (though not impossible) to evaluate.  Some
of the methods that we've developed over the last several weeks will
help, but we'll still need to use technology for a lot of the
resulting integrals.
** Example
What is the length of the curve defined by the function \(y = 2x^{3/2}
\) on the interval \( \left[ 1,4 \right]? \)

#+BEGIN_EXPORT latex 
\begin{tikzpicture}[domain=1:2,xscale=1,yscale=0.25]
\draw[help lines,step=0.5cm] (-0.1,-0.1) grid (4.1,16.1);
\draw[thick,->] (0,0) -- (4.1,0) node[right] {\(x \)};
\draw[thick,->] (0,0) -- (0,16.1) node[above] {\(y \)};

\draw[color=red,thick] plot ({\x*\x},{2*\x*\x*\x}) node[right] {\(f \left( x \right) = 2x^{3/2} \)};
\foreach \x in {1,2,3,4}
  \node[below] at (\x,-0.1) {\(\x \)};
\foreach \y in {2,4,...,16}
  \node[left] at (-0.1,\y) {\(\y \)};
\end{tikzpicture}
#+END_EXPORT
\vspace{10in}

** Example

** Example
What is the length of the parabola defined by \(y=x^2 \) on the
interval \( \left[ 0,2 \right] \)?
#+BEGIN_EXPORT latex 
\begin{tikzpicture}[domain=0:2,xscale=2,yscale=1]
\draw[help lines,step=0.25cm] (-0.1,-0.1) grid (2.1,4.1);
\draw[thick,->] (0,0) -- (2,0) node[right] {\(x \)};
\draw[thick,->] (0,0) -- (0,4) node[above] {\(y \)};
\draw[color=red,thick] plot (\x,{\x*\x}) node[right] {\(f \left( x \right) = x^2 \)};
\foreach \x in {0,0.5,...,2}
  \node[below] at (\x,-0.1) {\(\x \)};
\foreach \y in {0,1,...,4}
  \node[left] at (-0.1,\y) {\(\y \)};
\end{tikzpicture}
#+END_EXPORT
\vspace{10in}

** Example

** Example
Calculate the length of the curve defined by the function
\[
f \left( x \right) = \frac{x^4}{4} + \frac{1}{8x^2} \]
over the interval \(\left[ 1,2 \right] \).

#+BEGIN_EXPORT latex 
\begin{tikzpicture}[domain=0.1:2,samples=100,yscale=0.8,xscale=2]
\draw[help lines,step = 0.25] (-0.1,-0.1) grid (2.1,5);
\draw[->,thick] (-0.1,0) -- (2,0) node[right] {\(x \)};
\draw[->,thick] (0,-0.1) -- (0,5) node[above] {\(y \)};
\foreach \x in {0,0.5,...,2}
  \node[below] at (\x,-0.1) {\(\x \)};
\foreach \y in {0,1,...,5}
  \node[left] at (-0.1,\y) {\(\y \)};
\clip (-0.1,-0.1) rectangle (5.1,5);
\draw[thick,color=red] plot (\x,{0.25*pow(\x,4)+0.125*pow(\x,-2)}) node[right] {\(f \left( x \right) = \frac{x^4}{4} + \frac{1}{8x^2} \)};
\end{tikzpicture}

#+END_EXPORT
\vspace{10in}

** Example

** Arc length for functions of \(y \)
If we want to find the arc length of some smooth function of \(y \),
say \(x = g \left( y \right),\) the formula is almost identical:
*** Arc length (function of \(y \))                             :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
Suppose \(x = g \left( y \right) \) is a smooth function of \(y \) on
the interval \( \left[ c,d \right]. \)  Then the length of the curved
defined by \(x = g \left( y \right) \) is given by
\[
s = \int\limits_c^d \sqrt{1 + \left( g' \left( y \right)
\right)^2}\,dy. \]

** Example
Find the arc length of the curve defined by
\[
x = \frac{e^y+e^{-y}}{2} \]
for \(y \) on the interval \( \left[ 0,1 \right]. \)


#+BEGIN_EXPORT latex 
\begin{tikzpicture}[domain=0:2,scale=0.3\textwidth/3cm]
\draw[help lines,step=0.5] (-0.1,-0.1) grid (3,3);
\draw[thick,->] (-0.1,0) -- (3,0) node[right] {\(x \)};
\draw[thick,->] (0,-0.1) -- (0,3) node[above] {\(y \)};
\node[anchor = north east] at (0,0) {\(0 \)};
\foreach \x in {0.5,1,...,3}
  \node[below] at (\x,0) {\(\x \)};
\foreach \y in {0.5,1,...,3}
  \node[left] at (0,\y) {\(\y \)};
\clip (-0.1,-0.1) rectangle (3,3);
\draw[thick,color=red] plot ({0.5*(exp(\x)+exp(-\x))},\x) ;
\node[color=red] at (1,2) {\(x = \frac{e^y+e^{-y}}{2} \)};
\end{tikzpicture}
#+END_EXPORT
\vspace{10in}

** Example
