#+title: The Washer Method
#+author: Chase Mathison
#+date: 8 February 2024
#+email: cmathiso@su.edu
#+options: H:2 ':t ::t <:t email:t text:t todo:nil toc:nil
#+startup: showall
#+startup: indent
#+startup: hidestars
#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [presentation]
#+beamer_frame_level: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %5BEAMER_act(Act) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \definecolor{SUred}{rgb}{0.59375, 0, 0.17969} % SU red (primary)
#+latex_header: \definecolor{SUblue}{rgb}{0, 0.17578, 0.38281} % SU blue (secondary)
#+latex_header: \setbeamercolor{palette primary}{bg=SUred,fg=white}
#+latex_header: \setbeamercolor{palette secondary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette tertiary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette quaternary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{structure}{fg=SUblue} % itemize, enumerate, etc
#+latex_header: \setbeamercolor{section in toc}{fg=SUblue} % TOC sections
#+latex_header: % Override palette coloring with secondary
#+latex_header: \setbeamercolor{subsection in head/foot}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{date in head/foot}{bg=SUblue,fg=white}
#+latex_header: \institute[SU]{Shenandoah University}
#+latex_header: \titlegraphic{\includegraphics[width=0.5\textwidth]{\string~/Documents/suLogo/suLogo.pdf}}

* Announcements
** Announcements
1. Homework in MyOpenMath
2. Make sure to come to office hours if you have questions. (Friday
   via Zoom, 10 AM - 12 PM)
3. Quiz in Canvas today.

* The Lecture
** Other solids of revolution
Solids of revolution are a little more general than solids that always
have a circular cross section.  
For example, let's consider finding the volume of the solid generated by
rotating the region bounded by the curves
\[
y = x^2,\, y = \sqrt{x}\]
about the \(x- \)axis.
\vspace{10in}

** Other solids of revolution

** The washer method
In general, the cross section of a solid of revolution will *not* be
just a circle, but instead a "washer", or a circle with a smaller
circle cut out of the center.

Thankfully, it's still pretty easy to calculate the volume of a washer:
If the "big" circle has a radius of \(R \), and the "small" (cut out)
circle has a radius of \(r \), and the washer has a width of \(dx \),
then the volume of the washer is 
\[
 \]

From this, it's not hard to show the following.

** The washer method
*** The washer method                                           :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:

Suppose \(f \left( x \right) \) and \(g \left( x \right) \) are
continuous, nonnegative functions with \(f \left( x \right) \ge g
\left( x \right) \) over \( \left[ a,b \right] \).  Let \(R \) denote
the region bounded above by the graph of \(f \left( x \right) \) and
below by the graph of \(g \left( x \right) \), and by the lines \(x=a
\) and \(x=b \).  Then, the volume of the solid generated by rotating
\(R \) about the \(x- \)axis is given by
\[
 \]
 \phantom{butts}
 
 \phantom{butts}

** Example
Find the volume of the "napkin ring" generated by rotating the region
bounded above by \(y = \sqrt{4-x^2} \), and below by \(y = 1 \) about
the \(x- \)axis.

#+BEGIN_SRC python :exports none :results output :eval no-export
import matplotlib
matplotlib.use('Agg')
from matplotlib import rc
rc('font',**{'family':'serif','serif':['cm','Palatino']})
rc('text', usetex=True)
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

x = np.linspace(-np.sqrt(3),np.sqrt(3),1000)
t = np.linspace(0,2*np.pi,1000)
u,v = np.meshgrid(x,t)

X1 = u
Y1 = np.cos(v)
Z1 = np.sin(v)

X2 = u
Y2 = np.sqrt(4-u**2)*np.cos(v)
Z2 = np.sqrt(4-u**2)*np.sin(v)

fig = plt.figure()
ax = fig.gca(projection='3d')
ax.set_xlim3d(x.min(),x.max())
ax.set_ylim3d(-2,2)
ax.set_zlim3d(-2,2)
ax.plot_surface(X1,Y1,Z1,cmap='viridis',shade=True)
ax.plot_surface(X2,Y2,Z2,cmap='viridis',shade=True)
plt.savefig('../img/day007-ex02.png')
#+END_SRC

#+RESULTS:

#+BEGIN_EXPORT latex 
\begin{center}
\includegraphics[width=0.5\textwidth]{../img/day007-ex02.png}
\end{center}
#+END_EXPORT
\vspace{10in}

** Example

** Example
Find the volume of the solid generated by rotating the region bounded
above by the graph of \( y = x \), below by the graph of \( y = 1/x \)
and on the right by \(x = 4 \) about the \(x- \)axis.

#+BEGIN_SRC python :exports none :results output :eval no-export
import matplotlib
matplotlib.use('Agg')
from matplotlib import rc
rc('font',**{'family':'serif','serif':['cm','Palatino']})
rc('text', usetex=True)
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

x = np.linspace(1,4,1000)
t = np.linspace(0,2*np.pi,1000)
u,v = np.meshgrid(x,t)

X1 = u
Y1 = 1/u*np.cos(v)
Z1 = 1/u*np.sin(v)
X2 = u
Y2 = u*np.cos(v)
Z2 = u*np.sin(v)

# Cap
r1 = np.linspace(0.25,4,1000)
q,p = np.meshgrid(r1,t)

Xc = 4 + 0*q
Yc = q*np.cos(p)
Zc = q*np.sin(p)
fig = plt.figure()
ax = fig.gca(projection = '3d')
ax.set_xlim3d(1,4)
ax.set_ylim3d(-4,4)
ax.set_zlim3d(-4,4)
ax.plot_surface(X2,Y2,Z2,cmap='viridis',shade=False)
ax.plot_surface(X1,Y1,Z1,color='w',shade=True)
ax.plot_surface(Xc,Yc,Zc,cmap='viridis',shade=True)
plt.savefig('../img/day007-ex03.png')
#+END_SRC

#+RESULTS:

#+BEGIN_EXPORT latex 
\begin{center}
\includegraphics[width=0.5\textwidth]{../img/day007-ex03.png}
\end{center}
#+END_EXPORT
\vspace{10in}

** Example

** The washer method, again

Just like when we learned the disk method, we were also able to apply
it to volumes of revolution rotated about the \(y- \)axis, we can also
apply the washer method to volumes generated by rotating regions about
the \(y- \)axis with very little change.
*** The washer method (for functions of \(y \)) :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:

Suppose \(f \left( y \right) \) and \(g \left( y \right) \) are
continuous, nonnegative functions with \(f \left( y \right) \ge g
\left( y \right) \) over \( \left[ c,d \right] \).  Let \(Q \) denote
the region bounded on the right by the graph of \(f \left( y \right) \) and
on the left by the graph of \(g \left( y \right) \), and by the lines \(y=c
\) and \(y=d \).  Then, the volume of the solid generated by rotating
\(Q \) about the \(y- \)axis is given by
\[
 \]
 \phantom{butts}

 \phantom{butts}

** Example
Find the volume of the solid generated by rotating the region bounded
on the right by the graph of \(x = \cos y \), on the left by \(x =
\sin y \) and below by \(y = 0 \) about the \(y- \)axis.

#+BEGIN_SRC python :exports none :results output :eval no-export
import matplotlib
matplotlib.use('Agg')
from matplotlib import rc
rc('font',**{'family':'serif','serif':['cm','Palatino']})
rc('text', usetex=True)
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

y = np.linspace(0,np.pi/4,1000)
t = np.linspace(0,2*np.pi,1000)
u,v = np.meshgrid(y,t)

Y1 = u
X1 = np.cos(u)*np.cos(v)
Z1 = np.cos(u)*np.sin(v)
Y2 = u
X2 = np.sin(u)*np.cos(v)
Z2 = np.sin(u)*np.sin(v)

# Cap
r1 = np.linspace(0,1,1000)
q,p = np.meshgrid(r1,t)

Yc = 0 + 0*q
Xc = q*np.cos(p)
Zc = q*np.sin(p)

fig = plt.figure()
ax = fig.gca(projection='3d')
ax.plot_surface(X1,Y1,Z1,cmap='viridis',shade=True)
ax.plot_surface(X2,Y2,Z2,shade=False)
ax.plot_surface(Xc,Yc,Zc,shade=True)
plt.savefig('../img/day007-ex04.png')
#+END_SRC

#+RESULTS:

#+BEGIN_EXPORT latex 
\begin{center}
\includegraphics[width=0.5\textwidth]{../img/day007-ex04.png}
\end{center}
#+END_EXPORT
\vspace{10in}

** Example

** Example
BUT WHY JUST THE \(x- \) AND \(y- \) AXES?????

We can even find the volume of a solid that is generated by rotating a
region about any vertical or horizontal line.

Let's try to find the volume of the solid generated by rotating the
region bounded by the graphs of \(y = x \) and \(y = x^2 \) about the
line \(x = 2 \).

\vspace{10in}

** Example

** Next time
There's one final method that we can use to find these volumes of
revolution: cylindrical shells.  We'll learn how to use this method
next time.
