#+title: Mass and Moments
#+author: Chase Mathison
#+date: 19 March 2024
#+email: cmathiso@su.edu
#+options: H:2 ':t ::t <:t email:t text:t todo:nil toc:nil
#+startup: showall
#+startup: indent
#+startup: hidestars
#+startup: beamer
#+latex_class: beamer
#+latex_class_options: [presentation]
#+beamer_frame_level: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %5BEAMER_act(Act) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \definecolor{SUred}{rgb}{0.59375, 0, 0.17969} % SU red (primary)
#+latex_header: \definecolor{SUblue}{rgb}{0, 0.17578, 0.38281} % SU blue (secondary)
#+latex_header: \setbeamercolor{palette primary}{bg=SUred,fg=white}
#+latex_header: \setbeamercolor{palette secondary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette tertiary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{palette quaternary}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{structure}{fg=SUblue} % itemize, enumerate, etc
#+latex_header: \setbeamercolor{section in toc}{fg=SUblue} % TOC sections
#+latex_header: % Override palette coloring with secondary
#+latex_header: \setbeamercolor{subsection in head/foot}{bg=SUblue,fg=white}
#+latex_header: \setbeamercolor{date in head/foot}{bg=SUblue,fg=white}
#+latex_header: \institute[SU]{Shenandoah University}
#+latex_header: \titlegraphic{\includegraphics[width=0.5\textwidth]{\string~/Documents/suLogo/suLogo.pdf}}
#+latex_header: \usepackage{tikz}

* Announcements
** Announcements
1. Exam next Monday.
2. Office hours, 10am - 11am.

* Mass
** Center of mass and moment of masses on a line

We'll start with masses on a line.  If we have 2 (not necessarily
equal) masses on a line (think of a see-saw) then what would be the
point where we could perfectly balance that line?  This is called the
_\hspace*{1in}_. Let's find this: 
\vspace{10in}

** Center of mass
In general, if we have \(n \) point masses at \(n \) points, we have the
following:
*** Center of mass                                              :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
If \(m_1, m_2,\ldots m_n\) are masses at the points \(x_1,x_2,\ldots, x_n\) respectively, then we have the center of mass
\[
\bar{x} = \hspace{2in}\]

The value \(M = m_1x_1 + m_2x_2\) is called the _\hspace*{1in}_ of the system.

** Example
Find the center of mass and the moment of the system with respect to
the origin for the system of masses:
#+BEGIN_EXPORT latex 
\begin{align*}
m_1 = 2 kg \text{ at } x_1 = 0.2 m, \,\,& m_2 = 3 kg \text{ at } x_2 = 1 m, \\
m_3 = 7 kg \text{ at } x_3 = -0.5 m, \,\,& m_4 = 3.5 kg \text{ at } x_4 = -0.75 m
\end{align*}
#+END_EXPORT
\vspace{10in}

** Example

** Center of mass and moments of system in the plane
We can generalize the previous ideas to masses in the \(xy- \)plane.
Let's do this for 2 masses:
\vspace{10in}

** Center of mass and moments of system in the plane
Again, we can generalize this to \(n \) masses in the plane at \(n \)
points:
*** Center of mass and moments in the plane                     :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
If \(m_1,m_2,\ldots,m_n\) are point masses at the points \( \left(
x_1,y_1 \right), \left( x_2,y_2 \right),\ldots \left( x_n,y_n
\right)\) respectively, then we define the quantities
\[
M_x = \hspace{2in}\]
\[
M_y = \hspace{2in}\]
\[
\bar{x} = \hspace{2in}\]
\[
\bar{y} = \hspace{2in}\]

***                                                       :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
\vspace{10in}

** Example
Find the moments \(M_x,M_y \) and the center of mass of
the system of masses:
#+BEGIN_EXPORT latex 
\begin{align*}
m_1 = 2 kg,& \text{ at } \left( -1,3 \right) \\
m_2 = 6 kg,& \text{ at } \left( 1,1 \right) \\
m_3 = 4 kg,& \text{ at } \left( 2,-2 \right)
\end{align*}
#+END_EXPORT
\vspace{10in}

** Center of mass of a thin sheet
But what if we want to find the center of mass (or *centroid*, which
is the geometric center of an object) of a 2 dimensional
object, like a thin plate or some other thin object defined by a
function?

For what follows, we're going to find the moments about the \(x \) and
\(y \) axis and the center of mass for what's called a /lamina/, which
is a thin sheet of uniform density \(\rho \) represented as a region
in the \(xy- \)plane. 
\vspace{10in}

** Center of mass of a thin sheet
Can you guess what we're about to do?
\vspace{10in}

** Center of mass of a thin sheet

** Center of mass of a thin sheet
*** Center of mass of a thin sheet                              :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
Suppose \(R\) is the region bounded above by the continous function
\(y = f(x)\), below by \(y = 0\) and on the left and right by \(x =
a\) and \(x = b\) respectively. Let \(\rho\) (rho) denote the density of the associated lamina.  Then we have the following:

1. \(m = \hspace{2in}\)
2. \[M_x = \hspace{2in}\] and \[M_y = \hspace{2in}\]
3. \[\bar{x} = \hspace{2in}\] and \[\bar{y} = \hspace{2in}\]

***                                                       :B_ignoreheading:
:PROPERTIES:
:BEAMER_env: ignoreheading
:END:
\vspace{10in}

** Example

Let \(R \) be the region bounded by the curve \(y=\sqrt{x} \), the
\(x- \)axis and \(x=4 \).  This region has a constant density of \(2
\)kg/m\(^2 \) where \(x \) is measured in meters.  Find the center of mass of
this region (lamina).  What is the centroid?
\vspace{10in}

** Example

** More general lamina

Let's look at what happens if the lamina we are examining is defined
by an upper curve \(y = f(x) \) and a lower curve \(y = g(x), \) again
with a constant density \(\rho \) which has units of mass per
length\(^2 \).
\vspace{10in}

** More general lamina

In general, assume \(R\) is the region bounded above by the graph of
\(y = f(x)\), below by the graph of \(y = g(x)\) and on the left and
right by \(x = a\) and \(x = b\) respectively.  Also, suppose that the density of the associated lamina is the constant \(\rho.\) Then:

\vspace{10in}

** Example
Find the center of mass of the region bounded by the curves
\(y = 1-x^2 \) and \(y = x \), with a constant density of \(\rho=1
\)kg/m^2 where \(x \) is in m.
\vspace{10in}

** Example

** Example (The symmetry principal)
Find the center of mass of the region bounded by the curves \(y =
x^2-1 \) and \(\sqrt{1-x^2}\), with constant density of \(\rho=3
\)kg/m^2 where \(x \) is in m.
\vspace{10in}

** Example

** One more example
Find the center of mass of the region bounded by the curve \(y =
\cos(x) \) and the \(x- \)axis between \(x=-\pi/2 \) and \(x=\pi/2 \),
where the lamina has a constant density of \(1 \)kg/m\(^2 \) where \(x
\) is in meters.
\vspace{10in}
